title: Vendor Management Platform
description: Onboard and Execute your Vendor calls
theme: just-the-docs

url: https://github.com/natarajsundar/vmp

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
